-- MySQL Script generated by MySQL Workbench
-- 08/21/16 16:14:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bdBiblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdBiblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdBiblioteca` DEFAULT CHARACTER SET utf8 ;
USE `bdBiblioteca` ;

-- -----------------------------------------------------
-- Table `bdBiblioteca`.`Biblioteca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdBiblioteca`.`Biblioteca` (
  `idBiblioteca` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `ubicacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBiblioteca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdBiblioteca`.`Libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdBiblioteca`.`Libro` (
  `idLibro` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `autor` VARCHAR(45) NOT NULL,
  `Biblioteca_idBiblioteca` INT NOT NULL,
  PRIMARY KEY (`idLibro`),
  INDEX `fk_Libro_Biblioteca_idx` (`Biblioteca_idBiblioteca` ASC),
  CONSTRAINT `fk_Libro_Biblioteca`
    FOREIGN KEY (`Biblioteca_idBiblioteca`)
    REFERENCES `bdBiblioteca`.`Biblioteca` (`idBiblioteca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
